package com.kpi

import java.io.IOException

object Main {

    @Throws(IOException::class)
    @JvmStatic fun main(args: Array<String>) {
        val text = "EFFPQLMEHEMVPCPYFLMVHQLUHYTCETHQEKLPVMMVHQLUWEOLFPQLIVDLWLULMVHQLUCYAUHUYDUEOSQYATFFVSMUVOVWEPLPQVSPCHLYGETDYUVPQOGUYOOYWYETHQEKLPVMYWLSASVWDEWCPLSPYGDYYFWLSSYGGVPCYAEULMYOGYUPEKTLBVPQCYAOECASLVWFLRYGMYVWMVFLWMLNESVSNVLREOVWEPVYWSPEPVSPVMETPLSPSYUBQEPLILUOLPQYFCYAGLLTBVTTSQYBPQLKLSPULSATPPUCPYPQVWNYGBQEPBVTTQEHHLWVGPQLNLCMYWPEVWSSEOLMQEUEMPLUSEPFVGGLULWPHYSVPVYWSBVTTCYAUHUYDUEOSPVTTKLQEILMYUULMPTC"
        val alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        val criterionEvaluator = NGramCriterionEvaluator(3, "trigrams.txt")
        println(Decryptor().decrypt(text, alphabet, criterionEvaluator))
    }
}
